import { GoogleGenAI } from "@google/genai";

export const enhanceSignatureWithGemini = async (
  base64Image: string, 
  apiKey: string,
  model: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Remove data:image/png;base64, prefix if present
  const base64Data = base64Image.replace(/^data:image\/\w+;base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: `Take the provided handwritten signature image. 
            Output a cleaned version of this signature. 
            The output must be a high-contrast image with a pure white background and pure black ink.
            Remove any noise, shadows, or paper texture.
            Do not alter the shape of the letters.
            Keep the aspect ratio roughly 2:1 (width:height).`
          },
          {
            inlineData: {
              mimeType: 'image/png',
              data: base64Data
            }
          }
        ]
      }
    });

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI.");

  } catch (error) {
    console.error("Gemini Enhancement Failed:", error);
    throw error;
  }
};

export const recognizeSignatureTextWithGemini = async (
  base64Image: string,
  apiKey: string,
  model: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing");

  const ai = new GoogleGenAI({ apiKey });
  const base64Data = base64Image.replace(/^data:image\/\w+;base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: "Identify the handwritten Chinese name in this image. Return ONLY the characters of the name. Do not include pinyin, punctuation, or any other text."
          },
          {
            inlineData: {
              mimeType: 'image/png',
              data: base64Data
            }
          }
        ]
      }
    });
    
    return response.text?.trim() || "";
  } catch (error) {
    console.error("Gemini Recognition Failed:", error);
    throw error;
  }
};